<?php
// user_dashboard.php
session_start();

$allowed_roles = ['user', 'admin', 'super_admin'];
if (!isset($_SESSION['role']) || !in_array($_SESSION['role'], $allowed_roles)) {
    header("Location: ../../../../Public/Login_page/PHP/Frontend/Login_page_site.php");
    exit();
}

$user_name = $_SESSION['user_name'] ?? 'User';
$userRole = $_SESSION['role'] ?? 'user';

// Fix profile photo path - ensure it starts with / and includes full path
$profile_photo = $_SESSION['profile_photo'] ?? null;

if (!empty($profile_photo)) {
    // Remove any leading slashes to avoid double slashes
    $photo_path = ltrim($profile_photo, '/');

    // Build full URL path from your project root
    // Adjust this base path to match your project structure
    $base_url = '/ScanQuotient.v2/ScanQuotient.B';

    // Check if path already contains the base
    if (strpos($photo_path, 'Storage/') === 0) {
        $avatar_url = $base_url . '/' . $photo_path;
    } else {
        $avatar_url = $base_url . '/' . $photo_path;
    }
} else {
    // Default avatar path
    $avatar_url = '/ScanQuotient.v2/ScanQuotient.B/Storage/Public_images/default-avatar.png';
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ScanQuotient | Dashboard</title>
    <link rel="icon" type="image/png" href="../../../../Storage/Public_images/page_icon.png" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="../../CSS/admin_dashboard.css" />
</head>

<body>

    <header class="page-header">
        <div class="header-left">
            <a href="#" class="header-brand">ScanQuotient</a>
            <span class="header-tagline">Quantifying Risk. Strengthening Security.</span>
        </div>
        <div class="header-right">
            <!-- Profile Photo -->
            <img src="<?php echo $avatar_url; ?>" alt="Profile" class="header-profile-photo">

            <span class="welcome-text">
                Welcome,
                <?php echo htmlspecialchars($user_name); ?> |
                <span id="current-date"></span> |
                <span id="current-time"></span>
            </span>

            <button id="helpBtn" class="icon-btn" title="Help"><i class="fas fa-question-circle"></i></button>
            <a href="../../../../Private/My_profile/PHP/Frontend/My_profile.php" class="icon-btn" title="My Profile"><i
                    class="fas fa-user"></i></a>
            <a href="../../../../Public/Login_page/PHP/Frontend/Login_page_site.php" class="icon-btn" title="Logout"><i
                    class="fas fa-sign-out-alt"></i></a>
        </div>
    </header>

    <div id="helpModal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">
                    <i class="fas fa-shield-alt" style="margin-right: 8px; color: var(--brand-color);"></i>
                    ScanQuotient Platform Overview
                </h3>
                <button class="close">&times;</button>
            </div>

            <div class="modal-body">
                <ul class="info-list">

                    <li>
                        <i class="fas fa-chart-line"></i>
                        <div>
                            <strong>Admin Dashboard</strong>
                            <span>View real-time system status, device information, and overall platform
                                activity.</span>
                        </div>
                    </li>

                    <li>
                        <i class="fas fa-users-cog"></i>
                        <div>
                            <strong>User Management</strong>
                            <span>Create, manage, and monitor user accounts, roles, and account activity.</span>
                        </div>
                    </li>

                    <li>
                        <i class="fas fa-file-alt"></i>
                        <div>
                            <strong>Report Management</strong>
                            <span>Access and review vulnerability scan reports generated by the ScanQuotient
                                system.</span>
                        </div>
                    </li>

                    <li>
                        <i class="fas fa-shield-alt"></i>
                        <div>
                            <strong>Security Logs</strong>
                            <span>Monitor login activity, system alerts, and other security-related events.</span>
                        </div>
                    </li>

                    <li>
                        <i class="fas fa-credit-card"></i>
                        <div>
                            <strong>Subscriptions</strong>
                            <span>Manage user subscription plans, payment records, and service access levels.</span>
                        </div>
                    </li>

                    <li>
                        <i class="fas fa-envelope"></i>
                        <div>
                            <strong>Email Center</strong>
                            <span>Send notifications, system alerts, and communication emails to users.</span>
                        </div>
                    </li>

                    <li>
                        <i class="fas fa-comment-dots"></i>
                        <div>
                            <strong>User Feedback</strong>
                            <span>Review feedback submitted by users and monitor system improvement suggestions.</span>
                        </div>
                    </li>

                    <li>
                        <i class="fas fa-user-circle"></i>
                        <div>
                            <strong>Account Settings</strong>
                            <span>Update your administrator profile, password, and security settings.</span>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </div>

    <div class="app">
        <!-- Original Sidebar Preserved -->
        <aside class="sidebar">
            <div class="brand">Navigation</div>
            <nav>
                <a href="#" class="nav-btn active"><i class="fas fa-home"></i><span>Dashboard</span></a>
                <!-- User Management -->
                <a href="../../../../Private/User_management/PHP/Frontend/User_management.php" class="nav-btn">
                    <i class="fas fa-users"></i>
                    <span>User Management</span>
                </a>

                <!-- Report Management -->
                <a href="/ScanQuotient/ScanQuotient/Privatepages/Admin_dashboard/PHP/Frontend/admin_data_management.php"
                    class="nav-btn">
                    <i class="fas fa-file-alt"></i>
                    <span>Report Management</span>
                </a>

                <!-- Security -->
                <a href="/ScanQuotient/ScanQuotient/Privatepages/Admin_dashboard/PHP/Frontend/security.php"
                    class="nav-btn">
                    <i class="fas fa-shield-alt"></i>
                    <span>Security_logs</span>
                </a>
                <!-- Payments -->
                <a href="/ScanQuotient/ScanQuotient/Privatepages/Admin_dashboard/PHP/Frontend/payment_accounts.php"
                    class="nav-btn">
                    <i class="fas fa-credit-card"></i>
                    <span>Subscriptions</span>
                </a>

                <!-- Emails -->
                <a href="https://mail.google.com/mail/u/0/#inbox" target="_blank" class="nav-btn">
                    <i class="fas fa-envelope"></i>
                    <span>Emails</span>
                </a>

                <!-- Feedback -->
                <a href="../../../../Private/Feedback/PHP/Frontend/Feedback.php" class="nav-btn">
                    <i class="fas fa-comment-dots"></i>
                    <span>Feedback</span>
                </a>
                <div class="nav-divider"></div>
                <a href="../../../../Private/Ticket_support/PHP/Frontend/Admin_ticket_support.php" class="nav-btn"><i
                        class="fas fa-headset"></i><span>Help Center</span></a>
                <a href="../../../../Private/User_account/PHP/Frontend/User_subscription.php" class="nav-btn"><i
                        class="fas fa-user-cog"></i><span>Account</span></a>
                <button id="themeToggle" class="nav-btn theme-toggle-btn">
                    <i class="fas fa-sun"></i><span>Toggle Theme</span>
                </button>
            </nav>
        </aside>

        <main class="main">
            <div class="dashboard-grid">

                <!-- Top Card: Intelligence with Internal Sidebar -->
                <div class="intelligence-card">
                    <!-- Internal Sidebar -->
                    <div class="intel-sidebar">
                        <button class="intel-sidebar-btn active" onclick="switchCategory(0)">
                            <i class="fas fa-network-wired"></i>Network
                        </button>
                        <button class="intel-sidebar-btn" onclick="switchCategory(1)">
                            <i class="fas fa-fingerprint"></i>Browser
                        </button>
                        <button class="intel-sidebar-btn" onclick="switchCategory(2)">
                            <i class="fas fa-lock"></i>Security
                        </button>
                        <button class="intel-sidebar-btn" onclick="switchCategory(3)">
                            <i class="fas fa-microchip"></i>System
                        </button>
                    </div>

                    <!-- Content Area -->
                    <div class="intel-content-area">
                        <div class="intel-header">
                            <div class="intel-title" id="intelTitle">
                                <i class="fas fa-network-wired"></i>Network Intelligence
                            </div>
                        </div>

                        <button class="carousel-arrow prev" onclick="changeSlide(-1)"><i
                                class="fas fa-chevron-left"></i></button>
                        <button class="carousel-arrow next" onclick="changeSlide(1)"><i
                                class="fas fa-chevron-right"></i></button>

                        <div class="carousel-container" id="carouselContainer">
                            <!-- Slides injected by JS -->
                        </div>
                    </div>
                </div>


            </div>
    </div>

    </div>
    </main>
    </div>

    <footer class="page-footer">

        <!-- Left -->
        <div class="footer-left">
            <a href="#" class="footer-brand">ScanQuotient</a>
            <p>Quantifying Risk. Strengthening Security.</p>
        </div>

        <!-- Center -->
        <div class="footer-center">
            &copy;
            <?php echo date("Y"); ?> Authorized Security Testing
        </div>

        <!-- Right -->
        <div class="footer-right">
            Built for Web Security Assessment
        </div>

    </footer>
    <script src="../../Javascript/admin_dashboard.js" defer></script>

    <script>
        function updateDateTime() {
            const now = new Date();

            const options = {
                weekday: 'long',
                year: 'numeric',
                month: 'long',
                day: 'numeric'
            };

            document.getElementById("current-date").innerHTML =
                now.toLocaleDateString(undefined, options);

            document.getElementById("current-time").innerHTML =
                now.toLocaleTimeString();
        }

        updateDateTime();
        setInterval(updateDateTime, 1000);
    </script>
</body>

</html>